title: Sonya Castro
description: Backend Developer @ tyba | Systems Engineer | AWS Developer
url: ""
plugins:
  - jekyll-feed

sass:
  quiet_deps: true
  silence_deprecations: [import]
  style: compressed
  sass_dir: _sass
